### ISSUE TITLE
How to use something like the pcileech plugin with this?

### ISSUE THREAD

**Issue by rlewkowicz** [memflow/memflow-reclass-plugin#4]
I have compiled all the things, and for pci leech I even use debug since there's an issue for it talking about an inability to initialize. 

My reclass plugins folder:
![image](https://user-images.githubusercontent.com/17415445/148303622-b4c8439e-97ed-4cef-a0df-5d0f75537ec9.png)

When I try to attach to a process, I get: 
![image](https://user-images.githubusercontent.com/17415445/148303699-361b70fb-1d76-4d96-bf86-69c04031f173.png)

My toml:
```
connector = 'memflow_pcileech'
args = 'device=fpga'
parse_sections = false
```

I don't know where this thing spits logs to if anywhere and I can't make out this error

**Comment by ko1N** [comment]
Are you using the master or next branch currently?

Edit: In both cases for pcileech to work you at least need the FTD3xx.dll or compile the .so if you are on linux. You should find a link in the memflow-pcileech and also the main pcileech readmes.

**Comment by rlewkowicz** [comment]
I'm using master. and the over sized text was from windows scaling. I can check out next too. I was missing that ftd3xx.dll, whiuch I added, but I still cannot get the reclass plugin to read the memflow plugin. So went and opened a linux shell, put the connector dll in the linux path for memflow. From the memflow directory, I ran the command 
`cargo.exe  run --example read_phys --release -- -c memflow-pcileech FPGA` this failed, but it indicated that memflow was able to find the connector.

I have put this connector everywhere and set multiple paths. Memflow just can't find it from windows.

**Comment by rlewkowicz** [comment]
Ignore that. I'm too tired tonight. I'm not seeing the inventory come up with plugin still, but I did get windows working

**Comment by ko1N** [comment]
> I'm using master. and the over sized text was from windows scaling. I can check out next too. I was missing that ftd3xx.dll, whiuch I added, but I still cannot get the reclass plugin to read the memflow plugin. So went and opened a linux shell, put the connector dll in the linux path for memflow. From the memflow directory, I ran the command `cargo.exe run --example read_phys --release -- -c memflow-pcileech FPGA` this failed, but it indicated that memflow was able to find the connector.
> 
> I have put this connector everywhere and set multiple paths. Memflow just can't find it from windows.

The "next" version already has a full file log output which makes it easier to pinpoint those issues.
